### ISSUE TITLE
Receiving 422 error code when running scan

### ISSUE THREAD

**Issue by ssulei7** [rapid7/insightappsec-scan-github-actions#22]
Hi all, I am receiving the following when running this action:

```
Run rapid7/insightappsec-scan-github-actions@v1.2.0 
Scan gating query: vulnerability.severity = 'MEDIUM' 
Wait for scan complete: true 
Error: An error occurred with the scan: Error: Request failed with status code 422
```

Is there something that needs to be done on the Rapid7 side of things?

**Comment by ssulei7** [comment]
@ckearney-r7 any thoughts?

**Comment by ckearney-r7** [comment]
@ssulei7 is that the only error that's logged? - If so we need to update our logging. The API usually returns more detailed errors. You could try manually kicking off the scan and seeing if you get a more detailed error message, something like:

`curl --location -g --request POST 'https://{{region}}.api.insight.rapid7.com/ias/v1/scans' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{apiKey}}' \
--data-raw '{
    "scan_config": {
        "id": "{{scanConfigId}}"
    }
}'`

**Comment by ssulei7** [comment]
@ckearney-r7 Ah, seems my customer wasn't using the latest tag. I instructed them to update the tag of the task when they consume it. I see in your latest release you're using our core module for actions development; I think with that we can enable actions debug logging based on what I've seen in the code as well.

I will let you know how it pans out 😄 cheers!
